#!/usr/bin/env ruby
# Push record JSON to the Data Service, in parallel!

require 'rubygems'
require 'httparty'
require 'json'
require 'parallel'
require 'slop'

opts = Slop.parse do
  banner "Usage: push <--url=URL> <--file=FILE>"

  on 'url=', 'URL endpoint for POSTing records'
  on 'file=', 'JSON file with array of records to POST'
end

# Missing options check
if opts[:url].nil? || opts[:file].nil?
  puts opts
  exit 1
end

objects = JSON.parse(IO.read(opts[:file]))

puts "#{objects.count} records found in file"

Parallel.each_with_index(objects) do |record, i|

  response = HTTParty.post(opts[:url], body: JSON.generate(record))

  puts "#{i+1}/#{objects.count}|#{response.code} #{response.message}"
end
